LAB_DESCRIPTION="Basic SCION Topology with five routers, including core/leaf, containing issuing/non-issuing and voting/non-voting configurations."
LAB_VERSION=1.0
LAB_AUTHOR="Network Security Group"
LAB_WEB="https://netsec.ethz.ch"

scion1[0]="net14"
scion1[1]="net12"
scion1[2]="net13"
scion1[image]="kathara/scion"

scion2[0]="net12"
scion2[1]="net23"
scion2[2]="net25"
scion2[image]="kathara/scion"

scion3[0]="net13"
scion3[1]="net23"
scion3[2]="net34"
scion3[3]="net35"
scion3[image]="kathara/scion"

scion4[0]="net14"
scion4[1]="net34"
scion4[image]="kathara/scion"

scion5[0]="net25"
scion5[1]="net35"
scion5[image]="kathara/scion"
