!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 30
  ! announce my local network
  network 10.0.103.0/24

  ! register neighboring ASes
  neighbor 10.0.13.1 remote-as 10
  neighbor 10.0.23.2 remote-as 20

  ! automatically allows all incoming and outgoing prefix advertisements
  no bgp ebgp-requires-policy
!

