LAB_DESCRIPTION="Small BGP hierarchy with one t1att, three ISPs, and four customers."
LAB_VERSION=1.0
LAB_AUTHOR="Network Security Group"
LAB_WEB="https://netsec.ethz.ch"

## TIER 1
# -- AT-T --
t1att[0]="net1"
t1att[1]="net2"
t1att[2]="net3"
t1att[image]="kathara/frr"

## TIER 2
# -- Swisscom --
t2swisscom[0]="net1"
t2swisscom[1]="net4"
t2swisscom[2]="net5"
t2swisscom[image]="kathara/frr"

# -- SWITCH --
t2switch[0]="net2"
t2switch[1]="net4"
t2switch[2]="net6"
t2switch[3]="net7"
t2switch[image]="kathara/frr"

# -- Sunrise --
t2sunrise[0]="net3"
t2sunrise[1]="net8"
t2sunrise[2]="net9"
t2sunrise[image]="kathara/frr"

## TIER 3
# -- UBS --
t3ubs[0]="net5"
t3ubs[1]="netUBS"
t3ubs[image]="kathara/frr"

# -- UZH --
t3uzh[0]="net6"
t3uzh[1]="netUZH"
t3uzh[image]="kathara/frr"

# -- ETH --
t3eth[0]="net7"
t3eth[1]="net8"
t3eth[2]="netETH"
t3eth[image]="kathara/frr"

# -- ZKB --
t3zkb[0]="net9"
t3zkb[1]="netZKB"
t3zkb[image]="kathara/frr"