!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 2000
  ! originate my IP prefix
  ! TODO: Replace this route-map with the same route-map you would assign to a customer-AS
  ! This is a "hack" to ensure this local IP prefix is actually announced to all neighbors.
  network 10.0.102.0/24 route-map FROM_CUST

  ! register neighboring ASes
  neighbor 10.0.6.1 remote-as 200
  neighbor 10.0.6.1 route-map FROM_PRO  in
  neighbor 10.0.6.1 route-map TO_PRO out


! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! Below here, the shared ruleset in /shared/ruleset.conf is appended 
! automatically. You can use all of the shared routemaps in your
! neighbor definitions above.
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
