!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
  
  !EGRESS
  route-map EGRESS_BAD permit 10
   set local-preference 0 

  route-map EGRESS_GOOD permit 10 
    set local-preference 250

  !INGRESS
  route-map INGRESS_BADLINK_OUT permit 10
    set as-path prepend 10 10 10


router bgp 10
  !announce my local network
  network 10.0.101.0/24

  !register neighboring ASes
  neighbor 10.0.12.2 remote-as 20
  neighbor 10.0.13.3 remote-as 30


  !automatically allows all incoming and outgoing prefix advertisements
  no bgp ebgp-requires-policy

  !TODO: Enforce egress and ingress TE
  

  neighbor 10.0.13.3 route-map INGRESS_BADLINK_OUT out
  neighbor 10.0.13.3 route-map EGRESS_BAD in

  neighbor 10.0.12.2 route-map EGRESS_GOOD in