LAB_DESCRIPTION="BGP triangle with one bad link"
LAB_VERSION=1.0
LAB_AUTHOR="Network Security Group"
LAB_WEB="https://netsec.ethz.ch"

# -- AS10 --
as10[0]="net12"
as10[1]="net13"
as10[2]="netAS10"
as10[image]="kathara/frr"

# -- AS20 --
as20[0]="net12"
as20[1]="net23"
as20[2]="netAS20"
as20[image]="kathara/frr"

# -- AS30 --
as30[0]="net13"
as30[1]="net23"
as30[2]="netAS30"
as30[image]="kathara/frr"
