!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
bgp community 
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 10
  ! register neighboring ASes
  neighbor 10.0.1.2 remote-as 100
  ! TODO: Apply the appropriate route-maps to this neighbor 
  neighbor 10.0.1.2 route-map FROM_CUST  in
  neighbor 10.0.1.2 route-map TO_CUST out

  neighbor 10.0.2.2 remote-as 200
  ! TODO: Apply the appropriate route-maps to this neighbor 
  neighbor 10.0.2.2 route-map FROM_CUST  in
  neighbor 10.0.2.2 route-map TO_CUST out

  neighbor 10.0.3.2 remote-as 300
  ! TODO: Apply the appropriate route-maps to this neighbor 
  neighbor 10.0.3.2 route-map FROM_CUST  in
  neighbor 10.0.3.2 route-map TO_CUST out
!

! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! Below here, the shared ruleset in /shared/ruleset.conf is appended 
! automatically. You can use all of the shared routemaps in your
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! neighbor definitions above.
