!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 200
  ! register t1att AS as provider
  ! and assign in-/egress route-maps (FRR "functions").
  neighbor 10.0.2.1 remote-as 10
  neighbor 10.0.2.1 route-map TODO_ROUTEMAP  in
  neighbor 10.0.2.1 route-map TODO_ROUTEMAP out

  ! register t2swisscom AS as peer,
  ! and assign in-/egress route-maps (FRR "functions").
  neighbor 10.0.4.1 remote-as 100
  neighbor 10.0.4.1 route-map TODO_ROUTEMAP  in
  neighbor 10.0.4.1 route-map TODO_ROUTEMAP out
  
  ! register t3uzh AS as customer,
  ! and assign in-/egress route-maps (FRR "functions").
  neighbor 10.0.6.2 remote-as 2000
  neighbor 10.0.6.2 route-map TODO_ROUTEMAP  in
  neighbor 10.0.6.2 route-map TODO_ROUTEMAP out

  ! register t3eth AS as customer,
  ! and assign in-/egress route-maps (FRR "functions").
  neighbor 10.0.7.2 remote-as 3000
  neighbor 10.0.7.2 route-map TODO_ROUTEMAP  in
  neighbor 10.0.7.2 route-map TODO_ROUTEMAP out
!

! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! Below here, the shared ruleset in /shared/ruleset.conf is appended 
! automatically. You can use all of the shared routemaps in your
! neighbor definitions above.
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
