!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 20
  ! announce my local network
  network 10.0.102.0/24

  ! register neighboring ASes
  neighbor 10.0.12.1 remote-as 10
  neighbor 10.0.23.3 remote-as 30

  ! automatically allows all incoming and outgoing prefix advertisements
  no bgp ebgp-requires-policy
!
