
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! Implement all route-maps in this file.
! This file will be appended to the bottom of each router's configuration file.
! We suggest you group the route-maps based on their respective neighbor type
! (provider, peer, customer), however you are free to structure this file as you desire.
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

route-map TODO_ROUTEMAP permit 10

! - - - - - - - - - - Route Maps for Providers - - - - - - - - - -
route-map FROM_PRO permit 10
  set local-preference 50 
  set tag 100 

route-map TO_PRO deny 10
    match tag 200

route-map TO_PRO deny 20
    match tag 100

route-map TO_PRO permit 100

! - - - - - - - - - - Route Maps for Peer - - - - - - - - - -

route-map FROM_PEER permit 10 
    set local-preference 100
    set tag 200

route-map TO_PEER deny 10
  match tag 100  

route-map TO_PEER deny 20
  match tag 200  

route-map TO_PEER permit 100

! - - - - - - - - - - Route Maps for Customers - - - - - - - - - -

route-map FROM_CUST permit 10 
    set local-preference 200 
    set tag 300 

route-map TO_CUST permit 10