
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! Implement all route-maps in this file.
! This file will be appended to the bottom of each router's configuration file.
! We suggest you group the route-maps based on their respective neighbor type
! (provider, peer, customer), however you are free to structure this file as you desire.
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

route-map TODO_ROUTEMAP permit 10

! - - - - - - - - - - Route Maps for Providers - - - - - - - - - -

! TODO: Ingress route-map for providers

! TODO: Egress route-map for providers

! - - - - - - - - - - Route Maps for Peer - - - - - - - - - -

! TODO: Ingress route-map for peers

! TODO: Egress route-map for peers

! - - - - - - - - - - Route Maps for Customers - - - - - - - - - -

! TODO: Ingress route-map for customers

! TODO: Egress route-map for customers