!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  OSPF CONFIGURATION
!
! Enable log output:
debug ospf event
debug ospf packet all

! TODO-04: Adapt the correct link cost

! OSPF configuration block
router ospf
  ospf router-id 4.4.4.4
  network 10.0.34.0/24 area 0
  network 10.0.45.0/24 area 0
  network 10.0.46.0/24 area 0
  network 10.0.43.0/24 area 0
interface eth0
  ip ospf network point-to-point
  ip ospf cost 10
  ip ospf hello-interval 1
  ip ospf dead-interval 4
interface eth1
  ip ospf network point-to-point
  ip ospf cost 10
  ip ospf hello-interval 1
  ip ospf dead-interval 4
interface eth2
  ip ospf network point-to-point
  ip ospf cost 30
  ip ospf hello-interval 1
  ip ospf dead-interval 4
interface eth3
  ip ospf network point-to-point
  ip ospf cost 30
  ip ospf hello-interval 1
  ip ospf dead-interval 4
!
