!
! FRRouting configuration file
!
log file /var/log/frr/frr.log
!
!  BGP CONFIGURATION
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 100
  ! register t1att AS as provider
  ! and assign in-/egress route-maps (FRR "functions").
  neighbor 10.0.1.1 remote-as 10
  neighbor 10.0.1.1 route-map TODO_ROUTEMAP  in
  neighbor 10.0.1.1 route-map TODO_ROUTEMAP out

  ! register t2switch AS as peer,
  ! and assign in-/egress route-maps (FRR "functions").
  neighbor 10.0.4.2 remote-as 200
  neighbor 10.0.4.2 route-map TODO_ROUTEMAP  in
  neighbor 10.0.4.2 route-map TODO_ROUTEMAP out

  ! register t3ubs AS as customer,
  ! and assign in-/egress route-maps (FRR "functions").
  neighbor 10.0.5.2 remote-as 1000
  neighbor 10.0.5.2 route-map TODO_ROUTEMAP  in
  neighbor 10.0.5.2 route-map TODO_ROUTEMAP out


! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
! Below here, the shared ruleset in /shared/ruleset.conf is appended 
! automatically. You can use all of the shared routemaps in your
! neighbor definitions above.
! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
