LAB_DESCRIPTION="SCION triangle with one bad link"
LAB_VERSION=1.0
LAB_AUTHOR="Network Security Group"
LAB_WEB="https://netsec.ethz.ch"

# Router configurations
scion1[0]="net12"
scion1[1]="net13"
scion1[2]="net11"
scion1[image]="kathara/scion"

scion2[0]="net12"
scion2[1]="net23"
scion2[2]="net22"
scion2[image]="kathara/scion"

scion3[0]="net13"
scion3[1]="net23"
scion3[2]="net33"
scion3[image]="kathara/scion"

ip1[0]="net11"
ip1[image]="kathara/base"

ip2[0]="net22"
ip2[image]="kathara/base"

ip3[0]="net33"
ip3[image]="kathara/base"
