LAB_DESCRIPTION="First Steps in the Kathara framework. You are going to set up a toy example with a client and a server."
LAB_VERSION=1.0
LAB_AUTHOR="Network Security Group"
LAB_WEB="https://netsec.ethz.ch"

myclient[image]="kathara/base"
myserver[image]="kathara/base"

## TODO-01: connect the two devices to the correct Collision Domain
 myserver[0]="net12"
 myclient[0]="net12"
