LAB_DESCRIPTION="SCION triangle with one bad link"
LAB_VERSION=1.0
LAB_AUTHOR="Network Security Group"
LAB_WEB="https://netsec.ethz.ch"

# -- AS 42-ffaa:1:1 --
scion1[0]="net12"
scion1[1]="net13"
scion1[2]="netAS1"
scion1[image]="kathara/scion"

# -- AS 42-ffaa:1:2 --
scion2[0]="net12"
scion2[1]="net23"
scion2[2]="netAS2"
scion2[image]="kathara/scion"

# -- AS 42-ffaa:1:3 --
scion3[0]="net13"
scion3[1]="net23"
scion3[2]="netAS3"
scion3[image]="kathara/scion"
